version: 0.0
os: linux
files:
  - source: / 
    destination: /var/www/aipromptjournal
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root